In [3]:
# extracting atoms
from ccdc.io import MoleculeReader
import pandas as pd
import re
from gemmi import cif
import numpy as np

def ex_info(file, accuracy = 3):
    # Loading file to packages
    mol_1 = MoleculeReader(file)
    doc_1 = cif.read_file(file)
    
    #because of "0.XXXX" is the length of the coordinate of atoms,we need to extend the length by two
    accuracy = accuracy +2
    
    # adding chem_ID and atoms to dataframe
    List = []
    for f in mol_1[0].atoms:
        s = str(f)
        s = s[s.find("(")+1:s.find(")")]
        List.append(s)
    data_frame = pd.DataFrame(data = List, columns = ['atoms'])
    
    # don't know why the output from the atom function is doubled, I need to split this 
    data_frame = data_frame[:int(data_frame.size/2)]

    data_frame['Chem_ID'] = file
    data_frame = data_frame[['Chem_ID','atoms']]
    
    # adding atom number to dataframe
    List =[]
    for f in data_frame['atoms']:
        temp = re.findall(r'\d+', str(f))
        temp_str = int(str(temp[0]))
        List.append(temp_str)
    data_frame['atom#'] = List
    
    # adding 3D coordinate
    block = doc_1.sole_block()
    col_x = block.find_values('_atom_site_fract_x')
    List = []
    for n, x in enumerate(col_x):
        List.append(float((x[0:accuracy])))
    data_frame['X_3D'] = List
    

    col_y = block.find_values('_atom_site_fract_y')
    List = []
    for n, x in enumerate(col_y):
        List.append(float((x[0:accuracy])))
    data_frame['Y_3D'] = List
    
    col_z = block.find_values('_atom_site_fract_z')
    List = []
    for n, x in enumerate(col_z):
        List.append(float((x[0:accuracy])))
    data_frame['Z_3D'] = List
    return data_frame

In [4]:
ex_info('ja2206.cif')

       Chem_ID atoms  atom#   X_3D   Y_3D   Z_3D
0   ja2206.cif    S1      1  0.367  0.039  0.344
1   ja2206.cif    S2      2  0.427  0.457  0.677
2   ja2206.cif    C8      8  0.287  0.123  0.399
3   ja2206.cif    H8      8  0.272  0.031  0.326
4   ja2206.cif    C6      6  0.447  0.198  0.483
5   ja2206.cif    H6      6  0.463  0.118  0.426
6   ja2206.cif    C5      5  0.330  0.152  0.425
7   ja2206.cif    C4      4  0.404  0.186  0.464
8   ja2206.cif    C3      3  0.346  0.296  0.539
9   ja2206.cif    C2      2  0.389  0.314  0.561
10  ja2206.cif    C1      1  0.463  0.339  0.594
11  ja2206.cif    H1      1  0.491  0.370  0.623
12  ja2206.cif    S3      3  0.307  0.403  0.615
13  ja2206.cif    C7      7  0.271  0.246  0.495